apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chat-app
type: Opaque
data:
  POSTGRES_USER: Y2hhdGFwcA==
  POSTGRES_PASSWORD: Y2hhdGFwcC1sb2NhbC1vbmx5
  POSTGRES_DB: Y2hhdGFwcA==
