apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: chat-app
type: Opaque
data:
  DB_USERNAME: Y2hhdGFwcA==
  DB_PASSWORD: Y2hhdGFwcC1sb2NhbC1vbmx5
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
data:
  JWT_SECRET_KEY: Y2hhdGFwcC1qd3Qtc2VjcmV0
